Feat/#259 create death state
SillyBusinessInc/Moldbreaker pull request #264
Opened 2024-12-18 09:39 UTC by MustacheAltun

## Purpose of this PR:
creating death screen

## How to test:
go from menu scene to new game then die and see if that is the desired outcome.

### links: 
[Ticket](https://github.com/SillyBusinessInc/SillyBusinessGame/issues/259)

2024-12-18 14:39 UTC, PimMiii requested changes
minor question about why we're giving a method to all states, that's never called in those states, over simply using SetState() in the player script itself.

2024-12-18 14:39 UTC, PimMiii commented on Assets/Global/Scripts/Player/States/StateBase.cs
> +    public virtual void Death()
Is there a reason for giving all states this method, they never call,  rather than doing `SetState(states.Death)` in the OnDeath() of the player?

2024-12-18 14:39 UTC, PimMiii commented on Assets/Global/Scripts/Player/Player.cs
> +        currentState.Death();
this could simply be: `SetState(states.Death);` unless i'm missing something?

2024-12-18 15:09 UTC, PimMiii requested changes
Found bugged behavior

https://github.com/user-attachments/assets/7b1aca01-a290-4967-a949-1e71b3b577f3

![image](https://github.com/user-attachments/assets/81864626-db72-41d6-87f5-5557147844d0)
![image](https://github.com/user-attachments/assets/cd4fe2d9-4baa-4643-a4f1-9da2b277b980)

2024-12-19 09:35 UTC, WantToBeeMe approved these changes

2024-12-19 09:35 UTC, merged